const languages = {
    'bg': {
        celsius: "Целзий",
        cloudiness: "Облачност",
        compact: "Сбит",
        currently: "В момента",
        detailed: "Подробен",
        fahrenheit: "Фаренхайт",
        feelsLike: "Усеща се като",
        hourDataEnd: "Няма повече прогноза за показване",
        kmh: "Километра в час",
        lang: {
            bg: "Български",
            de: "Немски",
            en: "Английски"
        },
        language: "Език",
        lastUpdated: "Последна актуализация в",
        longDays: ["Неделя", "Понеделник", "Вторник", "Сряда", "Четвъртък", "Петък", "Събота"],
        mixed: "Смесено",
        mph: "Мили в час",
        ms: "Метрa в секунда",
        nextDayButton: "Вижте прогнозата за",
        ordinal: {
            1: "-ви",
            2: "-ри",
            3: "-ти",
            4: "-ти",
            5: "-ти",
            6: "-ти",
            7: "-ми",
            8: "-ми",
            9: "-ти",
            10: "-ти",
            11: "-ти",
            12: "-ти",
            13: "-ти",
            14: "-ти",
            15: "-ти",
            16: "-ти",
            17: "-ти",
            18: "-ти",
            19: "-ти",
            20: "-ти",
            21: "-ви",
            22: "-ри",
            23: "-ти",
            24: "-ти",
            25: "-ти",
            26: "-ти",
            27: "-ми",
            28: "-ми",
            29: "-ти",
            30: "-ти",
            31: "-ви",
        },
        search: {
            duplicate: "Местоположението вече е добавено",
            invalidInput: "Въведи валидно име на местоположение",
            limit: "Приложението поддържа само до 3 местоположения",
            load: "Зареждат се данни за времето в",
            placeholder: "Въведи местоположение тук"
        },
        serverError: "Възникна вътрешна грешка в сървъра",
        settings: "Настройки",
        shortDays: ["Нед", "Пон", "Вто", "Сря", "Чет", "Пет", "Съб"],
        sunrise: "Изгрев",
        sunset: "Залез",
        temperature: "Температура",
        update: "Обнови",
        view: "Изглед",
        windSpeed: "Скорост на вятъра"
    },
    'de': {
        celsius: "Celsius",
        cloudiness: "Trübung",
        compact: "Kurz",
        currently: "Zur Zeit",
        detailed: "Ausfuehrlich",
        fahrenheit: "Fahrenheit",
        feelsLike: "Fühlt sich an",
        hourDataEnd: "Keine Wettervorhersage mehr zu zeigen",
        kmh: "Kilometer pro Stunde",
        lang: {
            bg: "Bulgarisch",
            de: "Deutsch",
            en: "Englisch"
        },
        language: "Sprache",
        lastUpdated: "Zuletzt aktualisiert am",
        longDays: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
        mixed: "Gemischt",
        mph: "Meilen pro Stunde",
        ms: "Meter pro Sekunde",
        nextDayButton: "Sieh die Wettervorhersage für",
        ordinal: {
            1: "",
            2: "",
            3: "",
            4: "",
            5: "",
            6: "",
            7: "",
            8: "",
            9: "",
            10: "",
            11: "",
            12: "",
            13: "",
            14: "",
            15: "",
            16: "",
            17: "",
            18: "",
            19: "",
            20: "",
            21: "",
            22: "",
            23: "",
            24: "",
            25: "",
            26: "",
            27: "",
            28: "",
            29: "",
            30: "",
            31: "",
        },
        search: {
            duplicate: "Ort bereits hinzugefügt",
            invalidInput: " Gib einen gültigen Ortsnamen ein",
            limit: "Die Anwendung unterstützt nur bis zu 3 Standorte",
            load: "Wetterdaten werden geladen",
            placeholder: "Gib hier einen Ort ein"
        },
        serverError: "Serverfehler",
        settings: "Einstellungen",
        shortDays: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
        sunrise: "Sonnenaufgang",
        sunset: "Sonnenuntergang",
        temperature: "Temperatur",
        update: "Aktualisieren",
        view: "Ansicht",
        windSpeed: "Windgeschwindigkeit"
    },
    'en': {
        celsius: "Celcius",
        cloudiness: "Cloudiness",
        compact: "Compact",
        currently: "Currently",
        detailed: "Detailed",
        fahrenheit: "Fahrenheit",
        feelsLike: "Feels like",
        hourDataEnd: "No more weather to show",
        kmh: "Kilometers / hour",
        lang: {
            bg: "Bulgarian",
            de: "German",
            en: "English"
        },
        language: "Language",
        lastUpdated: "Last updated at",
        longDays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        mixed: "Mixed",
        mph: "Miles / hour",
        ms: "Meters / second",
        nextDayButton: "See the weather for",
        ordinal: {
            1: "st",
            2: "nd",
            3: "rd",
            4: "th",
            5: "th",
            6: "th",
            7: "th",
            8: "th",
            9: "th",
            10: "th",
            11: "th",
            12: "th",
            13: "th",
            14: "th",
            15: "th",
            16: "th",
            17: "th",
            18: "th",
            19: "th",
            20: "th",
            21: "st",
            22: "nd",
            23: "rd",
            24: "th",
            25: "th",
            26: "th",
            27: "th",
            28: "th",
            29: "th",
            30: "th",
            31: "st",
        },
        search: {
            duplicate: "Location already exists",
            invalidInput: "Please enter a valid location name",
            limit: "Sorry, the app supports up to 3 locations only",
            load: "Loading weather data for",
            placeholder: "Enter a location here"
        },
        serverError: "Internal server error",
        settings: "Settings",
        shortDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        sunrise: "Sunrise",
        sunset: "Sunset",
        temperature: "Temperature",
        update: "Update",
        view: "View",
        windSpeed: "Wind speed"
    },
}

export default languages